export enum DatabaseType {
  POSTGRES_LOGICAL = 'POSTGRES_LOGICAL',
  POSTGRES_PHYSICAL = 'POSTGRES_PHYSICAL',
  KINGBASE = 'KINGBASE',
  MYSQL = 'MYSQL',
  MARIADB = 'MARIADB',
  MONGODB = 'MONGODB',
}
